export const ACCOUNT_LIST_REQUEST = "ACCOUNT_LIST_REQUEST";
export const ACCOUNT_LIST_SUCCESS = "ACCOUNT_LIST_SUCCESS";

export const ADD_ACCOUNT_REQUEST = "ACCOUNT_LIST_REQUEST";
export const ADD_ACCOUNT_SUCCESS = "ACCOUNT_LIST_SUCCESS";
